In [132]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold,cross_val_score, train_test_split

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import OneHotEncoder,StandardScaler,OrdinalEncoder

from sklearn.metrics import mean_absolute_error

from sklearn.decomposition import PCA

from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR

In [133]:
pd.set_option('display.max_columns', None)

In [134]:
original_df = pd.read_csv('4.6_dataset_feature_selected.csv')
original_df

,sector,price,super_area,bedrooms,bathroom,balcony,age_possession,servant_room,luxury_category,parking,building_type
0,jharsa,0.70,1278.0000,2,2,2,1 to 5 year old,0,medium,1,low-rise
1,sohna,0.38,682.3526,2,2,2,1 to 5 year old,0,medium,2,mid-rise
2,sector 71,1.35,1198.0000,2,2,2,10+ year old,0,high,1,mid-rise
3,sector 82,3.40,3240.0000,4,4,2,0 to 1 year old,1,medium,2,low-rise
4,sohna,0.95,1065.0000,2,2,2,0 to 1 year old,0,low,1,low-rise
...,...,...,...,...,...,...,...,...,...,...,...
5587,sohna,0.88,1313.5000,4,4,2,5 to 10 year old,0,medium,2,mid-rise
5588,sector 99,3.75,3500.0000,4,4,3+,1 to 5 year old,1,high,2,mid-rise
5589,sector 92,1.45,1628.0000,3,4,3+,1 to 5 year old,1,medium,1,mid-rise
5590,sector 65,3.85,2916.6800,3,3,2,0 to 1 year old,0,medium,0,high-rise
5591,sector 70a,3.50,2150.0000,3,3,3,1 to 5 year old,0,high,3,high-rise

In [135]:
df = original_df.copy()
df

,sector,price,super_area,bedrooms,bathroom,balcony,age_possession,servant_room,luxury_category,parking,building_type
0,jharsa,0.70,1278.0000,2,2,2,1 to 5 year old,0,medium,1,low-rise
1,sohna,0.38,682.3526,2,2,2,1 to 5 year old,0,medium,2,mid-rise
2,sector 71,1.35,1198.0000,2,2,2,10+ year old,0,high,1,mid-rise
3,sector 82,3.40,3240.0000,4,4,2,0 to 1 year old,1,medium,2,low-rise
4,sohna,0.95,1065.0000,2,2,2,0 to 1 year old,0,low,1,low-rise
...,...,...,...,...,...,...,...,...,...,...,...
5587,sohna,0.88,1313.5000,4,4,2,5 to 10 year old,0,medium,2,mid-rise
5588,sector 99,3.75,3500.0000,4,4,3+,1 to 5 year old,1,high,2,mid-rise
5589,sector 92,1.45,1628.0000,3,4,3+,1 to 5 year old,1,medium,1,mid-rise
5590,sector 65,3.85,2916.6800,3,3,2,0 to 1 year old,0,medium,0,high-rise
5591,sector 70a,3.50,2150.0000,3,3,3,1 to 5 year old,0,high,3,high-rise

In [136]:
X = df.drop(columns = ['price'])
Y= df['price']

In [137]:
y_transformed = np.log1p(Y)

#### Applying column tranformations and building pipeline

In [138]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5592 entries, 0 to 5591
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sector           5592 non-null   object
 1   super_area       5592 non-null   float64
 2   bedrooms         5592 non-null   int64
 3   bathroom         5592 non-null   int64
 4   balcony          5592 non-null   object
 5   age_possession   5592 non-null   object
 6   servant_room     5592 non-null   int64
 7   luxury_category  5592 non-null   object
 8   parking          5592 non-null   int64
 9   building_type    5592 non-null   object
dtypes: float64(1), int64(4), object(5)
memory usage: 437.0+ KB

In [139]:
#creating column transformer for preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

ordinal_order = [
    ['0', '1', '2', '3', '3+'],
    ['under construction','0 to 1 year old','1 to 5 year old', '5 to 10 year old','10+ year old' ],
    ['low','medium','high'],
]

ordinal_cols = [4,5,7]

preprocessor = ColumnTransformer(
    transformers= [
        ('scaling', StandardScaler(), ['super_area','bedrooms','bathroom','servant_room','parking']),
        ('ordinal', OrdinalEncoder(categories=ordinal_order),ordinal_cols),
        ('onehot', OneHotEncoder(handle_unknown='ignore',drop='first'),['sector','building_type'])
				],
    remainder='passthrough'
)

In [140]:
#building pipeline
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold,cross_val_score,train_test_split

def scorer (model_name,model):
	output =[]
	output.append(model_name)
	pipeline = Pipeline(
		[('preprocessor',preprocessor),
			('model',model)
			]
	)

	#K-fold cross validation
	kfold = KFold(n_splits = 10, shuffle= True)
	scores = cross_val_score(pipeline,X,y_transformed, cv= kfold , scoring='r2')

	output.append(scores.mean())

	#train test split
	x_train,x_test,y_train,y_test = train_test_split(X,y_transformed,test_size=0.2)

	pipeline.fit(x_train,y_train)

	y_pred = pipeline.predict(x_test)

	y_pred = np.expm1(y_pred)

	output.append(mean_absolute_error(np.expm1(y_test),y_pred))

	return output

In [141]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,ExtraTreesRegressor,GradientBoostingRegressor,AdaBoostRegressor
from sklearn.neural_network import MLPRegressor

model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [142]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [143]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [144]:
model_df.sort_values(['mae'])

                 name        r2       mae
6         extra trees  0.937542  0.281722
10            xgboost  0.931854  0.336632
5       random forest  0.924783  0.342647
9                 mlp  0.931319  0.362709
4       decision tree  0.883170  0.392043
1                 svr  0.921141  0.426404
0          linear_reg  0.875345  0.491782
2               ridge  0.883608  0.493243
7   gradient boosting  0.870988  0.502010
8            adaboost  0.716225  0.787886
3               LASSO -0.001141  1.239021

In [165]:
## Extra trees pipeline
pipeline_1 = Pipeline(
		[('preprocessor',preprocessor),
			('model',ExtraTreesRegressor())
			]
	)

k_fold = KFold(n_splits =10 , shuffle=True)
scores_1 = cross_val_score(estimator=pipeline_1, X=X, y=y_transformed, cv= k_fold , scoring= 'r2' )

x_train,x_test,y_train,y_test = train_test_split(X,y_transformed,test_size=0.2)
pipeline_1.fit(x_train,y_train)
y_pred = pipeline_1.predict(x_test)
y_pred = np.expm1(y_pred)

mae_1 = mean_absolute_error(np.expm1(y_test),y_pred)
mae_1

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

0.3116430348707561

In [167]:
scores_1.mean(),scores_1.std(), mae_1

(0.9367213964199774, 0.007270412788880864, 0.3116430348707561)

### Making an ensemble of models

In [168]:
from sklearn.ensemble import VotingRegressor

etr = ExtraTreesRegressor(n_estimators=100,)
rfr = RandomForestRegressor(n_estimators=100)
xgb = XGBRegressor(n_estimators=100)

ensemble = VotingRegressor([
    ('etr', etr),
    ('rfr', rfr),
    ('xgb', xgb)
])


pipeline_2 = Pipeline([('preprocessor',preprocessor),
					 ('model',ensemble)]
	)

#K-fold cross validation
kfold = KFold(n_splits = 10, shuffle= True)
scores_2 = cross_val_score(pipeline_2,X,y_transformed, cv= kfold , scoring='r2')


#train test split
x_train,x_test,y_train,y_test = train_test_split(X,y_transformed,test_size=0.2)

pipeline_2.fit(x_train,y_train)

y_pred = pipeline_2.predict(x_test)

y_pred = np.expm1(y_pred)

mae_2 = mean_absolute_error(np.expm1(y_test),y_pred)
mae_2

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

0.3190789206997326

In [169]:
scores_2.mean(), scores_2.std(),mae_2

(0.9397300455693014, 0.010100709731172983, 0.3190789206997326)

-- No improvement over ExtraTrees pipeline

In [ ]:
#testing on real world data
#https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-krisumi-waterfall-residences-sector-36a-gurgaon-2538-sq-ft-spid-Z81368679
data = [['sector 36a',2538,3,3,'3+','0 to 1 year old',1,'high',2,'high-rise']]
cols = X.columns

testing_df= pd.DataFrame(data,columns=cols)
testing_df = testing_df.astype(X.dtypes.to_dict())

np.expm1(pipeline.predict(testing_df))


data = [['sector 110a',1407,3,3,'2','1 to 5 year old',0,'medium',1,'mid-rise']]
cols = X.columns

testing_df= pd.DataFrame(data,columns=cols)
testing_df = testing_df.astype(X.dtypes.to_dict())

np.expm1(pipeline.predict(testing_df))
np.expm1(pipeline_2.predict(testing_df))

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

array([1.82712422])

### Hyper parameter tuning

In [170]:
#creating column transformer for preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

ordinal_order = [
    ['0', '1', '2', '3', '3+'],
    ['under construction','0 to 1 year old','1 to 5 year old', '5 to 10 year old','10+ year old' ],
    ['low','medium','high'],
]

ordinal_cols = [4,5,7]

preprocessor = ColumnTransformer(
    transformers= [
        ('scaling', StandardScaler(), ['super_area','bedrooms','bathroom','servant_room','parking']),
        ('ordinal', OrdinalEncoder(categories=ordinal_order),ordinal_cols),
        ('onehot', OneHotEncoder(handle_unknown='ignore',drop='first'),['sector','building_type'])
				],
    remainder='passthrough'
)

In [171]:
#build pipeline
from sklearn.model_selection import GridSearchCV

param_grid = {
    'regressor__n_estimators': [50, 100, 200, 300],
    'regressor__max_depth': [None, 10, 20, 30],
    'regressor__max_samples':[0.1, 0.25, 0.5, 1.0],
    'regressor__max_features': ['auto', 'sqrt'],
    'regressor__bootstrap': [True]
}

pipeline_3 = Pipeline(
    [('preprocessor',preprocessor),
     ('regressor',ExtraTreesRegressor())])

kfold = KFold(n_splits=10, shuffle=True, random_state=42)
search = GridSearchCV(pipeline_3, param_grid, cv=kfold, scoring='r2', n_jobs=-1, verbose=4)
search.fit(X,y_transformed)

Fitting 10 folds for each of 128 candidates, totalling 1280 fits
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.844 total time=   0.2s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.858 total time=   0.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.833 total time=   0.2s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.895 total time=   0.4s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.855 total time=   0.2s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.902 total time=   0.4s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.862 total time=   0.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.860 total time=   0.2s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.865 total time=   0.8s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.851 total time=   0.4s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.842 total time=   0.2s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.877 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.889 total time=   0.4s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.903 total time=   0.8s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.853 total time=   0.4s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.862 total time=   0.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.855 total time=   1.2s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.843 total time=   0.2s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.889 total time=   0.4s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.840 total time=   0.4s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.861 total time=   0.3s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.865 total time=   0.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.846 total time=   0.7s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.851 total time=   0.2s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.857 total time=   0.4s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.852 total time=   0.4s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.879 total time=   0.4s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.898 total time=   0.8s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.895 total time=   0.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.846 total time=   0.5s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.896 total time=   0.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.865 total time=   0.8s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.844 total time=   1.2s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.845 total time=   0.8s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.880 total time=   0.4s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.857 total time=   0.4s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.884 total time=   0.9s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.897 total time=   0.9s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.902 total time=   0.4s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.840 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.852 total time=   0.8s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.891 total time=   0.7s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.844 total time=   0.9s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.892 total time=   0.8s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.896 total time=   0.6s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.903 total time=   1.9s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.865 total time=   1.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.863 total time=   0.8s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.858 total time=   0.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.882 total time=   0.9s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.909 total time=   0.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.844 total time=   1.2s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.849 total time=   0.8s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.846 total time=   0.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.902 total time=   0.8s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.905 total time=   0.9s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.891 total time=   1.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.887 total time=   1.8s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.892 total time=   2.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.917 total time=   0.7s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.906 total time=   0.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.884 total time=   0.8s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.867 total time=   1.1s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.853 total time=   1.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.914 total time=   0.7s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.905 total time=   0.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.884 total time=   1.7s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.904 total time=   1.8s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.858 total time=   1.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.919 total time=   0.8s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.841 total time=   1.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.914 total time=   1.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.909 total time=   1.6s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.902 total time=   0.8s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.889 total time=   2.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.864 total time=   1.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.892 total time=   1.8s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.915 total time=   0.7s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.897 total time=   1.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.923 total time=   1.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.923 total time=   0.8s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.900 total time=   1.5s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.848 total time=   1.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.922 total time=   2.9s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.889 total time=   1.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.901 total time=   1.7s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.903 total time=   2.4s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.924 total time=   1.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.917 total time=   1.6s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.906 total time=   1.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.920 total time=   1.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.907 total time=   1.4s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.912 total time=   1.4s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.886 total time=   1.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.887 total time=   2.3s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.903 total time=   2.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.923 total time=   1.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.912 total time=   4.5s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.923 total time=   2.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.932 total time=   4.2s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.893 total time=   2.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.913 total time=   2.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.905 total time=   1.4s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.901 total time=   2.4s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.917 total time=   2.8s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.917 total time=   2.3s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.883 total time=   2.4s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.697 total time=   0.1s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.688 total time=   0.1s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.683 total time=   0.1s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.715 total time=   0.2s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.689 total time=   0.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.901 total time=   2.4s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.710 total time=   0.2s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.711 total time=   0.3s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.675 total time=   0.1s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.905 total time=   3.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.723 total time=   0.1s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.703 total time=   0.2s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.715 total time=   0.1s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.911 total time=   4.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.685 total time=   0.1s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.706 total time=   0.2s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.688 total time=   0.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.691 total time=   0.2s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.688 total time=   0.3s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.922 total time=   2.8s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.684 total time=   0.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.920 total time=   2.2s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.709 total time=   0.2s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.691 total time=   0.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.682 total time=   0.1s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.913 total time=   4.5s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.719 total time=   0.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.700 total time=   0.4s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.679 total time=   0.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.687 total time=   0.4s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.707 total time=   0.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.714 total time=   0.4s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.899 total time=   2.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.676 total time=   0.5s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.679 total time=   0.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.726 total time=   0.3s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.908 total time=   2.8s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.718 total time=   0.5s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.921 total time=   2.2s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.704 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.687 total time=   0.4s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.915 total time=   2.7s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.712 total time=   0.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.723 total time=   0.5s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.706 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.706 total time=   0.5s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.692 total time=   0.5s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.922 total time=   4.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.720 total time=   0.4s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.892 total time=   2.5s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.699 total time=   0.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.678 total time=   0.1s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.725 total time=   0.1s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.930 total time=   2.1s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.701 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.696 total time=   0.2s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.710 total time=   0.2s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.696 total time=   0.1s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.698 total time=   0.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.702 total time=   0.2s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.682 total time=   0.2s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.707 total time=   0.1s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.924 total time=   4.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.677 total time=   0.1s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.909 total time=   2.8s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.719 total time=   0.2s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.685 total time=   0.2s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.721 total time=   0.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.718 total time=   0.2s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.701 total time=   0.1s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.722 total time=   0.2s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.697 total time=   0.2s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.717 total time=   0.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.694 total time=   0.2s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.697 total time=   0.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.698 total time=   0.4s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.698 total time=   0.4s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.910 total time=   3.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.702 total time=   0.4s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.691 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.719 total time=   0.4s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.683 total time=   0.4s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.715 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.729 total time=   0.5s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.713 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.914 total time=   2.2s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.698 total time=   0.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.697 total time=   0.6s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.696 total time=   0.6s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.714 total time=   0.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.686 total time=   0.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.720 total time=   0.6s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.680 total time=   0.7s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.720 total time=   0.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.682 total time=   0.2s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.712 total time=   0.7s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.680 total time=   0.1s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.906 total time=   4.2s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.693 total time=   0.1s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.692 total time=   0.2s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.726 total time=   0.6s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.719 total time=   0.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.673 total time=   0.1s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.712 total time=   0.7s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.714 total time=   0.2s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.712 total time=   0.2s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.716 total time=   0.1s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.702 total time=   0.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.692 total time=   0.3s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.702 total time=   0.2s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.698 total time=   0.3s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.683 total time=   0.3s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.922 total time=   2.2s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.711 total time=   0.3s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.723 total time=   0.3s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.682 total time=   0.3s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.718 total time=   0.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.690 total time=   0.3s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.694 total time=   0.3s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.937 total time=   4.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.692 total time=   0.6s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.701 total time=   0.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.694 total time=   0.5s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.706 total time=   0.6s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.912 total time=   4.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.680 total time=   0.5s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.724 total time=   0.6s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.723 total time=   0.6s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.716 total time=   0.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.707 total time=   0.5s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.720 total time=   0.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.936 total time=   2.2s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.702 total time=   0.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.694 total time=   0.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.702 total time=   0.8s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.687 total time=   0.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.725 total time=   0.9s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.676 total time=   0.9s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.916 total time=   4.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.719 total time=   0.9s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.720 total time=   0.9s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.690 total time=   0.2s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.693 total time=   0.2s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.720 total time=   0.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.713 total time=   0.8s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.685 total time=   0.2s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.706 total time=   0.8s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.730 total time=   0.2s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.652 total time=   0.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.730 total time=   0.2s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.694 total time=   0.2s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.703 total time=   0.2s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.715 total time=   0.2s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.925 total time=   2.3s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.705 total time=   0.4s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.709 total time=   0.3s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.696 total time=   0.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.687 total time=   0.3s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.724 total time=   0.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.721 total time=   0.3s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.926 total time=   4.6s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.691 total time=   0.4s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.715 total time=   0.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.716 total time=   0.4s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.698 total time=   0.4s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.906 total time=   4.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.696 total time=   0.7s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.706 total time=   0.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.700 total time=   0.7s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.682 total time=   0.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.722 total time=   0.8s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.675 total time=   0.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.715 total time=   0.7s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.921 total time=   2.2s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.708 total time=   0.7s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.713 total time=   0.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.704 total time=   0.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.700 total time=   1.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.923 total time=   4.2s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.698 total time=   1.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.705 total time=   1.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.683 total time=   1.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.722 total time=   1.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.675 total time=   1.1s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.718 total time=   0.9s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.724 total time=   1.1s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.715 total time=   1.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=10, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.696 total time=   1.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.838 total time=   0.1s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.808 total time=   0.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.923 total time=   4.6s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.822 total time=   0.2s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.805 total time=   0.2s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.845 total time=   0.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.836 total time=   0.2s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.816 total time=   0.3s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.836 total time=   0.5s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.810 total time=   0.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.827 total time=   0.3s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.816 total time=   0.2s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.811 total time=   0.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.803 total time=   0.2s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.826 total time=   0.9s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.836 total time=   0.3s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.838 total time=   0.2s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.810 total time=   0.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.828 total time=   0.3s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.821 total time=   0.2s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.813 total time=   0.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.809 total time=   0.4s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.831 total time=   0.3s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.923 total time=   4.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.842 total time=   0.6s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.838 total time=   0.3s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.834 total time=   0.2s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.815 total time=   0.9s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.821 total time=   0.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.838 total time=   0.2s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.807 total time=   0.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.832 total time=   0.3s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.829 total time=   0.6s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.853 total time=   0.3s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.812 total time=   0.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.848 total time=   0.2s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.918 total time=   4.6s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.851 total time=   0.3s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.838 total time=   0.9s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.828 total time=   0.3s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.833 total time=   0.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.863 total time=   0.3s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.827 total time=   0.6s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.837 total time=   0.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.849 total time=   0.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.826 total time=   0.6s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.811 total time=   0.9s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.835 total time=   0.5s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.815 total time=   0.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.858 total time=   0.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.845 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.850 total time=   0.5s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.816 total time=   0.9s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.840 total time=   0.9s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.829 total time=   0.5s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.851 total time=   1.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.851 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.851 total time=   0.4s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.845 total time=   0.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.826 total time=   0.8s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.814 total time=   0.9s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.824 total time=   0.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.828 total time=   1.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.844 total time=   0.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.839 total time=   0.9s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.846 total time=   0.4s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.844 total time=   1.1s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.918 total time=   4.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.856 total time=   1.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.842 total time=   0.4s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.922 total time=   6.8s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.841 total time=   1.6s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.913 total time=   4.4s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.843 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.824 total time=   0.9s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.835 total time=   1.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.865 total time=   0.4s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.851 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.857 total time=   1.1s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.825 total time=   0.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.852 total time=   0.4s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.863 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.924 total time=   1.2s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.845 total time=   1.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.834 total time=   1.5s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.856 total time=   0.4s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.847 total time=   0.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.854 total time=   1.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.834 total time=   0.9s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.863 total time=   0.7s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.919 total time=   1.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.848 total time=   0.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.841 total time=   1.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.866 total time=   0.8s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.855 total time=   1.6s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.849 total time=   0.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.922 total time=   1.2s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.859 total time=   0.7s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.864 total time=   1.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.848 total time=   0.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.844 total time=   1.6s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.920 total time=   4.9s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.855 total time=   0.8s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.827 total time=   1.5s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.862 total time=   0.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.923 total time=   1.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.832 total time=   1.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.832 total time=   0.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.838 total time=   1.5s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.927 total time=   1.1s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.849 total time=   1.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.856 total time=   1.6s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.852 total time=   0.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.867 total time=   1.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.918 total time=   7.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.852 total time=   0.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.912 total time=   1.4s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.847 total time=   1.6s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.853 total time=   0.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.855 total time=   1.6s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.852 total time=   2.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.842 total time=   0.5s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.867 total time=   1.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.918 total time=   1.2s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.863 total time=   0.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.851 total time=   1.5s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.824 total time=   0.5s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.927 total time=   5.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.856 total time=   1.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.866 total time=   0.5s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.860 total time=   1.5s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.931 total time=   1.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.866 total time=   0.5s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.839 total time=   2.2s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.868 total time=   0.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.855 total time=   0.5s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.843 total time=   1.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.862 total time=   1.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.844 total time=   1.5s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.854 total time=   1.3s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.857 total time=   1.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.869 total time=   0.9s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.1s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.866 total time=   2.1s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.864 total time=   2.1s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.854 total time=   1.1s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.862 total time=   1.1s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.851 total time=   2.2s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.857 total time=   3.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.854 total time=   1.1s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.849 total time=   1.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.921 total time=   7.1s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.835 total time=   1.9s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.835 total time=   2.1s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.838 total time=   0.2s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.851 total time=   1.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.838 total time=   0.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.854 total time=   0.2s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.833 total time=   0.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.860 total time=   0.3s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.845 total time=   2.4s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.841 total time=   0.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.867 total time=   1.1s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.864 total time=   0.2s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.863 total time=   0.2s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.850 total time=   2.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.854 total time=   0.2s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.844 total time=   0.2s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.867 total time=   2.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.835 total time=   0.4s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.864 total time=   2.2s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.849 total time=   0.4s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.852 total time=   3.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.830 total time=   1.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.839 total time=   0.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.845 total time=   0.4s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.864 total time=   0.3s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.859 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.861 total time=   0.4s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.848 total time=   0.4s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.844 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.835 total time=   0.5s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.854 total time=   2.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.872 total time=   2.1s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.848 total time=   0.7s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.850 total time=   0.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.861 total time=   0.8s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.864 total time=   2.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.830 total time=   0.8s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.836 total time=   0.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.839 total time=   0.9s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.866 total time=   3.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.854 total time=   2.1s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.864 total time=   0.9s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.860 total time=   0.9s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.867 total time=   1.9s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.842 total time=   1.2s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.862 total time=   2.1s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.843 total time=   0.8s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.854 total time=   0.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.929 total time=   7.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.838 total time=   1.1s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.850 total time=   1.9s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.854 total time=   1.1s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.858 total time=   1.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.860 total time=   2.1s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.838 total time=   2.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.855 total time=   2.2s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.865 total time=   1.2s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.863 total time=   1.2s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.841 total time=   1.2s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.838 total time=   1.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.880 total time=   0.4s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.879 total time=   0.4s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.868 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.866 total time=   0.3s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.888 total time=   0.4s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.873 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.888 total time=   0.4s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.855 total time=   1.2s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.849 total time=   1.2s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.890 total time=   0.4s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.892 total time=   0.4s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.882 total time=   0.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.878 total time=   0.8s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.884 total time=   0.7s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.874 total time=   0.7s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.871 total time=   0.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.889 total time=   0.8s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.853 total time=   3.0s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.867 total time=   3.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.874 total time=   0.8s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.890 total time=   0.8s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.892 total time=   0.8s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.890 total time=   0.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.875 total time=   0.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.871 total time=   1.4s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.881 total time=   1.4s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.883 total time=   1.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.874 total time=   1.5s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.894 total time=   1.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.932 total time=   7.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.873 total time=   3.0s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.856 total time=   3.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.894 total time=   1.4s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.872 total time=   1.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.890 total time=   1.5s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.887 total time=   1.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.881 total time=   1.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.881 total time=   2.3s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.877 total time=   2.3s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.881 total time=   2.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.878 total time=   2.3s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.892 total time=   2.3s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.866 total time=   3.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.873 total time=   2.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.895 total time=   0.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.891 total time=   0.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.892 total time=   0.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.889 total time=   0.7s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.904 total time=   0.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.890 total time=   2.3s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.892 total time=   2.3s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.893 total time=   2.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.881 total time=   2.3s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.880 total time=   0.7s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.904 total time=   0.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.902 total time=   0.6s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.902 total time=   0.7s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.895 total time=   0.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=20, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.862 total time=   2.9s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.900 total time=   1.1s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.891 total time=   1.1s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.894 total time=   1.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.892 total time=   1.2s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.888 total time=   1.2s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.906 total time=   1.2s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.913 total time=   7.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.904 total time=   1.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.905 total time=   1.2s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.909 total time=   1.3s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.896 total time=   1.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.895 total time=   2.4s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.888 total time=   2.3s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.897 total time=   2.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.893 total time=   2.3s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.905 total time=   2.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.886 total time=   2.3s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.905 total time=   2.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.902 total time=   2.3s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.896 total time=   2.3s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.907 total time=   2.5s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.898 total time=   3.4s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.890 total time=   3.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.896 total time=   3.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.897 total time=   3.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.900 total time=   0.8s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.923 total time=   7.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.888 total time=   3.3s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.906 total time=   3.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.904 total time=   3.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.899 total time=   0.9s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.901 total time=   0.9s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.899 total time=   0.9s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.911 total time=   0.9s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.894 total time=   0.9s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.911 total time=   3.6s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.902 total time=   0.9s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.902 total time=   3.5s
[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.912 total time=   0.9s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.909 total time=   0.9s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.902 total time=   0.8s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.899 total time=   3.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.904 total time=   1.6s
[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.901 total time=   1.7s
[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.899 total time=   1.6s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.901 total time=   1.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.913 total time=   1.6s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.905 total time=   1.6s
[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.891 total time=   1.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.922 total time=   2.0s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.911 total time=   2.0s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=100;, score=0.907 total time=   2.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.938 total time=   7.7s
[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.904 total time=   3.9s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.902 total time=   3.9s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.905 total time=   3.9s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.904 total time=   4.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.892 total time=   3.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.913 total time=   3.7s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.907 total time=   3.6s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.919 total time=   3.5s
[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.912 total time=   3.5s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=200;, score=0.906 total time=   3.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 1/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.904 total time=   4.9s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 2/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.900 total time=   5.1s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 3/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.900 total time=   4.9s
[CV 4/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.903 total time=   5.0s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.928 total time=   7.7s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 6/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.893 total time=   5.4s
[CV 5/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.914 total time=   5.5s
[CV 7/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.909 total time=   5.4s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 8/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.917 total time=   5.3s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

[CV 9/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.910 total time=   4.8s
[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=30, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.906 total time=   4.8s

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:540: FitFailedWarning:
640 fits failed out of a total of 1280.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
194 fits failed with the following error:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of ExtraTreesRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
446 fits failed with the following error:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of ExtraTreesRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/model_selection/_search.py:1103: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.8514378  0.85186513
 0.8532814  0.85387195 0.89050936 0.8931131  0.89343683 0.89411839
 0.91104623 0.91161464 0.91251677 0.91388326 0.92187723 0.92290243
 0.92439657 0.92481018        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.69525198 0.69996095 0.70069857 0.70291763 0.70189307 0.70265249
 0.70447477 0.70636278 0.69822751 0.69940751 0.70618629 0.70432669
 0.70118918 0.70616569 0.70232316 0.70372063        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.81970047 0.82300135 0.82511242 0.8247765
 0.84276584 0.84255054 0.84436489 0.84507395 0.84882057 0.85287112
 0.85337051 0.85308864 0.85392058 0.85557858 0.85740448 0.85896366
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.84903957 0.84786262
 0.84856903 0.85032111 0.88059222 0.88172033 0.88262798 0.88365453
 0.89536304 0.89852403 0.89752402 0.8990127  0.90304326 0.90547711
 0.90649276 0.90573968]
  warnings.warn(

[CV 10/10] END regressor__bootstrap=True, regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=1.0, regressor__n_estimators=300;, score=0.923 total time=   5.4s

GridSearchCV(cv=KFold(n_splits=10, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('scaling',
                                                                         StandardScaler(),
                                                                         ['super_area',
                                                                          'bedrooms',
                                                                          'bathroom',
                                                                          'servant_room',
                                                                          'parking']),
                                                                        ('ordinal',
                                                                         OrdinalEncoder(categories=[['0',
                                                                                                     '1',
                                                                                                     '2',
                                                                                                     '3',
                                                                                                     '3+'],
                                                                                                    ['under '
                                                                                                     'construction',
                                                                                                     '0 '
                                                                                                     'to '
                                                                                                     '1 '
                                                                                                     'ye...
                                                                         OneHotEncoder(drop='first',
                                                                                       handle_unknown='ignore'),
                                                                         ['sector',
                                                                          'building_type'])])),
                                       ('regressor', ExtraTreesRegressor())]),
             n_jobs=-1,
             param_grid={'regressor__bootstrap': [True],
                         'regressor__max_depth': [None, 10, 20, 30],
                         'regressor__max_features': ['auto', 'sqrt'],
                         'regressor__max_samples': [0.1, 0.25, 0.5, 1.0],
                         'regressor__n_estimators': [50, 100, 200, 300]},
             scoring='r2', verbose=4)

In [172]:
pipeline_3 = search.best_estimator_

In [173]:
search.best_params_

{'regressor__bootstrap': True,
 'regressor__max_depth': None,
 'regressor__max_features': 'sqrt',
 'regressor__max_samples': 1.0,
 'regressor__n_estimators': 300}

In [174]:
search.best_score_

0.9248101834919948

In [175]:
x_train,x_test,y_train,y_test = train_test_split(X,y_transformed,test_size=0.2)

pipeline_3.fit(x_train,y_train)

y_pred = pipeline_3.predict(x_test)

y_pred = np.expm1(y_pred)

mae_3 = mean_absolute_error(np.expm1(y_test),y_pred)
mae_3

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

0.3773416327098663

In [176]:
search.best_score_,mae_3

(0.9248101834919948, 0.3773416327098663)

-- Somehow, performing worse

In [177]:
model_data = [['ExtraTreesRegressor',scores_1.mean(), scores_1.std(),mae_1],
              ['Ensemble models',scores_2.mean(), scores_2.std(),mae_2],
              ['ExtraTrees Parameter tunes',search.best_score_, np.nan,mae_3]]
pd.DataFrame(model_data, columns = ['Model name','scores_mean', 'scores_std','mae'])

                   Model name  scores_mean  scores_std       mae
0         ExtraTreesRegressor     0.936721    0.007270  0.311643
1             Ensemble models     0.939730    0.010101  0.319079
2  ExtraTrees Parameter tunes     0.924810         NaN  0.377342

-- Based on this choosing pipeline 1

# Exporting final model and dataset

In [179]:
#creating column transformer for preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

ordinal_order = [
    ['0', '1', '2', '3', '3+'],
    ['under construction','0 to 1 year old','1 to 5 year old', '5 to 10 year old','10+ year old' ],
    ['low','medium','high'],
]

ordinal_cols = [4,5,7]

preprocessor = ColumnTransformer(
    transformers= [
        ('scaling', StandardScaler(), ['super_area','bedrooms','bathroom','servant_room','parking']),
        ('ordinal', OrdinalEncoder(categories=ordinal_order),ordinal_cols),
        ('onehot', OneHotEncoder(handle_unknown='ignore',drop='first'),['sector','building_type'])
				],
    remainder='passthrough'
)

final_pipe =  Pipeline(
		[('preprocessor',preprocessor),
			('model',ExtraTreesRegressor())
			]
	)

final_pipe.fit(X,y_transformed)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('scaling', StandardScaler(),
                                                  ['super_area', 'bedrooms',
                                                   'bathroom', 'servant_room',
                                                   'parking']),
                                                 ('ordinal',
                                                  OrdinalEncoder(categories=[['0',
                                                                              '1',
                                                                              '2',
                                                                              '3',
                                                                              '3+'],
                                                                             ['under '
                                                                              'construction',
                                                                              '0 '
                                                                              'to '
                                                                              '1 '
                                                                              'year '
                                                                              'old',
                                                                              '1 '
                                                                              'to '
                                                                              '5 '
                                                                              'year '
                                                                              'old',
                                                                              '5 '
                                                                              'to '
                                                                              '10 '
                                                                              'year '
                                                                              'old',
                                                                              '10+ '
                                                                              'year '
                                                                              'old'],
                                                                             ['low',
                                                                              'medium',
                                                                              'high']]),
                                                  [4, 5, 7]),
                                                 ('onehot',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['sector',
                                                   'building_type'])])),
                ('model', ExtraTreesRegressor())])

In [180]:
#export pipeline
import pickle

with open('5.2_piepline.pkl', 'wb') as file:
    pickle.dump(pipeline_1,file)

In [181]:
#export dataset
with open('5.3_dataset_final.pkl','wb') as file:
    pickle.dump(X,file)